version: "3.4"

services:
  admin:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    command: tail -f /dev/null
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
