version: '3.4'

services:
  admin:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    command: npm run start:dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
      
